name: administrador_de_tareas
description: "Administrador de tareas"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  flutter_timezone: ^4.1.1
  get_it: ^8.0.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
